language: python
python:
  - "3.5.2"
install:
  - pip install nose
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DB=postgresql
script: 
  - nosetests --exe -v --with-coverage --cover-package=app
  - coveralls
after_success:
 - coveralls
notifications:
  slack:
    on_success: never
    on_failure: never
  email: false